name: Build / Beta

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install dependencies
              run: npm i

            - name: Generate Seed Database
              run: npm run seed

            - name: Build and package
              run: npm run package

            - name: Upload installer
              uses: actions/upload-artifact@v4
              with:
                  name: eve-sov-tool-win-installer
                  path: dist/*.exe

            - name: Upload portable zip
              uses: actions/upload-artifact@v4
              with:
                  name: eve-sov-tool-win-portable
                  path: dist/*.zip
